import type { APIRoute } from 'astro';

export const GET: APIRoute = () => {
  const body = "# Cartransportwithpersonalitems\n\nCartransportwithpersonalitems publishes agent-readable discovery resources for customer-authorised household moving quotes, vehicle transport quotes, callbacks, and quote API documentation.\n\n## Contact\nWebsite: https://cartransportwithpersonalitems.com.au\nContact: https://quoting.cartransportwithpersonalitems.com.au/contact\nQuote system: https://quoting.cartransportwithpersonalitems.com.au/\n\n## Human quote flows\n- Household quote: https://quoting.cartransportwithpersonalitems.com.au/quote/household\n- Vehicle quote: https://quoting.cartransportwithpersonalitems.com.au/quote/vehicle\n- Contact page: https://quoting.cartransportwithpersonalitems.com.au/contact\n\n## Agent/API resources\n- Agent guide: https://cartransportwithpersonalitems.com.au/agents/\n- Agent examples: https://cartransportwithpersonalitems.com.au/agents/examples/\n- Markdown summary: https://cartransportwithpersonalitems.com.au/index.md\n- AI catalog: https://cartransportwithpersonalitems.com.au/.well-known/ai-catalog.json\n- Agent skills index: https://cartransportwithpersonalitems.com.au/.well-known/agent-skills/index.json\n- Quote host agent guide: https://quoting.cartransportwithpersonalitems.com.au/agents\n- Quote host examples: https://quoting.cartransportwithpersonalitems.com.au/agents/examples\n- OpenAPI alias: https://cartransportwithpersonalitems.com.au/openapi.json\n- Canonical OpenAPI: https://quoting.cartransportwithpersonalitems.com.au/openapi.json\n- Quote capability alias: https://cartransportwithpersonalitems.com.au/quote-capability.json\n- Canonical quote capability: https://quoting.cartransportwithpersonalitems.com.au/quote-capability.json\n- AI plugin alias: https://cartransportwithpersonalitems.com.au/.well-known/ai-plugin.json\n- Quote host AI catalog: https://quoting.cartransportwithpersonalitems.com.au/.well-known/ai-catalog.json\n- Quote host LLM guidance: https://quoting.cartransportwithpersonalitems.com.au/llms.txt\n\n## Public agent API endpoints\n- Household quote API: https://quoting.cartransportwithpersonalitems.com.au/api/v1/household-quotes/assistant/submit\n- Vehicle quote API: https://quoting.cartransportwithpersonalitems.com.au/api/v1/vehicle-quotes/assistant/submit\n- Callback request API: https://quoting.cartransportwithpersonalitems.com.au/api/v1/callbacks/assistant/request\n\n## Agent rules\n- Customer consent is required before submitting quote or callback requests.\n- Use the quote host OpenAPI schema and capability manifest as the canonical contract.\n- Public host-aware API submissions should omit tenant unless Moveroo has supplied an agreed tenant slug.\n";

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=300"
}
  });
};
